services:
    postgres:
        image: postgres:latest
        container_name: migration-repro-postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=test
